<rule-set name="archetypeService.save.animal.pet.before"
    xmlns="http://drools.org/rules"    
    xmlns:java="http://drools.org/semantics/java"
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:schemaLocation="http://drools.org/rules rules.xsd
    				   http://drools.org/semantics/java java.xsd">
    				   
    <rule name="Set Active End Time for animal.pet">
        <parameter identifier="pet">
        	<java:class>org.openvpms.component.business.domain.im.party.Animal</java:class>
        </parameter>
        <parameter identifier="service">
        	<java:class>org.openvpms.component.business.service.archetype.IArchetypeService</java:class>
        </parameter>
        <java:condition>pet.getEntityRelationships().size() > 0</java:condition>
        <java:consequence>
            org.openvpms.component.business.service.ruleengine.AnimalPetRules.setActiveEndDates(service, pet);
        </java:consequence>
    </rule>

</rule-set> 