<rule-set name="person.uppercaseName"
    xmlns="http://drools.org/rules"    
    xmlns:java="http://drools.org/semantics/java"
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:schemaLocation="http://drools.org/rules rules.xsd
    				   http://drools.org/semantics/java java.xsd">
    				   
    <rule name="Change the persons name to upper case">
        <parameter identifier="person">
        	<java:class>org.openvpms.component.business.domain.im.party.Party</java:class>
        </parameter>
        <java:condition>person.getArchetypeId().getShortName().equals("person.person")</java:condition>
        <java:consequence>
        	if (person.getName() != null) {
	            person.setName(person.getName().toUpperCase());
            }
        </java:consequence>
    </rule>

</rule-set> 