<rule-set name="person.copyName"
    xmlns="http://drools.org/rules"    
    xmlns:java="http://drools.org/semantics/java"
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:schemaLocation="http://drools.org/rules rules.xsd
    				   http://drools.org/semantics/java java.xsd">
    				   
    <application-data identifier="prefix">java.lang.String</application-data>

    <rule name="Change the persons name to upper case">
        <parameter identifier="person">
        	<java:class>org.openvpms.component.business.domain.im.party.Party</java:class>
        </parameter>
        <parameter identifier="tarString">
        	<java:class>java.lang.StringBuffer</java:class>
        </parameter>
        
        <java:condition>person.getArchetypeId().getShortName().equals("party.person")</java:condition>
        <java:consequence>
        	if (prefix != null) {
        		tarString.append(prefix);
        	}
	        tarString.append(person.getName());
        </java:consequence>
    </rule>

</rule-set> 