<rule-set name="archetypeService.remove.party.person.after"
    xmlns="http://drools.org/rules"    
    xmlns:java="http://drools.org/semantics/java"
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:schemaLocation="http://drools.org/rules rules.xsd
    				   http://drools.org/semantics/java java.xsd">
    				   
    <rule name="Remove after">
        <parameter identifier="person">
        	<class>org.openvpms.component.business.domain.im.party.Party</class>
        </parameter>
        <java:condition>true</java:condition>
        <java:consequence>
            person.getDetails().put("remove_after", Boolean.TRUE);
        </java:consequence>
    </rule>

</rule-set> 