<rule-set name="archetypeService.save.party.patientpet.before"
    xmlns="http://drools.org/rules"    
    xmlns:java="http://drools.org/semantics/java"
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:schemaLocation="http://drools.org/rules rules.xsd
    				   http://drools.org/semantics/java java.xsd">
    				   
    <rule name="Check Patient Relationships">
        <parameter identifier="party">
        	<java:class>org.openvpms.component.business.domain.im.party.Party</java:class>
        </parameter>
        <parameter identifier="service">
        	<java:class>org.openvpms.component.business.service.archetype.IArchetypeService</java:class>
        </parameter>
        <java:condition>party.getEntityRelationships().size() > 0</java:condition>
        <java:consequence>
            org.openvpms.archetype.rules.PartyRelationshipRules.checkPatientRelationships(service, party);
        </java:consequence>
    </rule>

</rule-set> 