<rule-set name="calculateTax"
    xmlns="http://drools.org/rules"    
    xmlns:java="http://drools.org/semantics/java"
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:schemaLocation="http://drools.org/rules rules.xsd
    				   http://drools.org/semantics/java java.xsd">
    				   
    <rule name="Calculate Tax">
        <parameter identifier="service">
             <java:class>org.openvpms.component.business.service.archetype.IArchetypeService</java:class>
        </parameter>
        <parameter identifier="act">
             <java:class>org.openvpms.component.business.domain.im.act.FinancialAct</java:class>
        </parameter>
        <java:consequence>
            org.openvpms.archetype.rules.financial.TaxRules.calculateTax(service,act);
        </java:consequence>
    </rule>
</rule-set> 