<rule-set name="archetypeService.save.before"
    xmlns="http://drools.org/rules"    
    xmlns:java="http://drools.org/semantics/java"
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:schemaLocation="http://drools.org/rules rules.xsd
    				   http://drools.org/semantics/java java.xsd">
    				   
    <rule name="Always Print">
        <parameter identifier="person">
        	<java:class>org.openvpms.component.business.domain.im.party.Person</java:class>
        </parameter>
        <java:condition>person.getName() != null</java:condition>
        <java:consequence>
            org.openvpms.component.business.service.ruleengine.PartyPersonRules.onSaveMessage(person);
        </java:consequence>
    </rule>

</rule-set> 